### ISSUE TITLE
Compatible  but no longer working...

### ISSUE THREAD

**Issue by Killerstrike1234** [SugarBarrel/ECTD#4]
I installed both rougelibs 3.3.0 and ECTD 3.0.0 but even though it loaded the patch (mod) ECTD no longer Edits Character Through the Description and the characters I made from the previous version no longer work. :( (maybe its just that way for me could you show me the way you have the folders (MACOS) organized it worked before but idk honestly )

[LogOutput.log](https://github.com/Abbysssal/ECTD/files/7890501/LogOutput.log)

**Comment by Abbysssal** [comment]
```
[Error  :   BepInEx] Failed to run [RogueLibsPatcher.RogueLibsPatcher] when patching [Assembly-CSharp]. This assembly will not be patched. Error: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.TypeLoadException: Could not load type 'System.Func`2' from assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
```

It looks like the problem is with RogueLibsPatcher. I'm not sure what could be causing that, since the missing type was introduced in one of the earliest versions of .NET. Try reinstalling .NET or Mono - that might resolve the issue.

**Comment by Killerstrike1234** [comment]
ok thanks ill tell you if that works

**Comment by Killerstrike1234** [comment]
Yea I feel like that would work I just can't find where to get .net or mono , and where I should replace the install.

**Comment by Abbysssal** [comment]
https://www.mono-project.com/docs/getting-started/install/mac/

**Comment by Killerstrike1234** [comment]
once I install am I all set? I installed but nothing changed (sorry if I am being clueless), what should I do next its a little confusing since a lot of the directions I see on the internet are for Windows

**Comment by Abbysssal** [comment]
I found a problem in RogueLibs, but I'm not sure if it's related to this issue or not. Download [RogueLibs.zip](https://github.com/Abbysssal/ECTD/files/7893953/RogueLibs.zip) and replace the RogueLibsCore.dll and RogueLibsPatcher.dll in the BepInEx directory.

If nothing changed, send the LogOutput.log. Also make sure that you've extracted all of the files and directories from BepInEx_unix_5.4.18.0.zip file to the game's directory:
```
- Streets of Rogue
  - BepInEx
    - core
      - ...
  - doorstop_libs
    - libdoorstop_x64.dylib
    - libdoorstop_x64.so
    - libdoorstop_x86.dylib
    - libdoorstop_x86.so
```
You can also try updating all other packages (Mono could have unlisted dependencies) and then restarting your computer. If that doesn't help, create an issue on [BepInEx's repository](https://github.com/BepInEx/BepInEx/issues), they might be able to help.

**Comment by Killerstrike1234** [comment]
ok got it(hope this works!)thanks!

**Comment by Aspace2create** [comment]
hey im getting the same error running this on Mac im trying to continue modding on macOS but the mods I wanted to use as well as the new ones return the same error as the one above how can I fix this I organized the files correctly can you elaborate the solution stated above and if it was fixed or if there is a fix I can be made aware of?

**Comment by Aspace2create** [comment]
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

**Comment by SugarBarrel** [comment]
I think I know what's wrong. Try using this version of RogueLibsPatcher:
[RogueLibsPatcher.zip](https://github.com/SugarBarrel/ECTD/files/10326200/RogueLibsPatcher.zip)
I removed any `System.Func'2` references from the patcher, so this error shouldn't occur now.

**Comment by Aspace2create** [comment]
ty this and using the lates version of mono and SOR fixed my problem

**Comment by Aspace2create** [comment]
however I have a question how would I use mods that required an older version of RougeLibs

**Comment by Aspace2create** [comment]
that is without uninstalling it anyway I could use it universally?

**Comment by SugarBarrel** [comment]
RogueLibs v2? It wouldn't work, since it's a major release, basically a complete rewrite.

**Comment by Aspace2create** [comment]
oh ok makes sense, also I don't know how to make mods for SOR on macOS, I know the code but the csproj and the other stuff are foreign to me as it appears to default to windows any macOS specific tutorial on this?

**Comment by Aspace2create** [comment]
could you send me a working template for the roguelibs mod creation without the complicated after build command specifications?

**Comment by Aspace2create** [comment]
ohh I fixed it ty
